<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <Using Include="AlvorKit.Engine" />
        <Using Include="Craftdig" />
        <Using Include="Craftdig.App" />
        <Using Include="Craftdig.App.Frontend" />
        <Using Include="Craftdig.Dimension" />
        <Using Include="Craftdig.Dimension.Frontend" />
        <Using Include="Craftdig.Dimension.Unit">
            <Static>true</Static>
        </Using>
        <Using Include="Craftdig.Module" />
        <Using Include="Craftdig.Module.Frontend" />
        <Using Include="Craftdig.World" />
        <Using Include="Craftdig.World.Frontend" />
        <Using Include="AlvorKit.OpenGL" />
        <Using Include="AlvorKit.OpenGL.Layer" />
        <Using Include="AlvorKit.Graphics2D" />
        <Using Include="AlvorKit.Graphics2D.Fonts" />
        <Using Include="AlvorKit.Windowing" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="$(AlvorKitRoot)src/AlvorKit.ECS.Generator/AlvorKit.ECS.Generator.csproj"
            OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
        <ProjectReference Include="..\Craftdig.Dimension\Craftdig.Dimension.csproj" />
        <ProjectReference Include="..\Craftdig.World.Frontend\Craftdig.World.Frontend.csproj" />
    </ItemGroup>

</Project>
