<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <Using Include="AlvorKit.ECS.Indexed" />
        <Using Include="Craftdig" />
        <Using Include="Craftdig.App" />
        <Using Include="Craftdig.Dimension" />
        <Using Include="Craftdig.Dimension.Unit">
            <Static>true</Static>
        </Using>
        <Using Include="Craftdig.Module" />
        <Using Include="Craftdig.World" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="$(AlvorKitRoot)src/AlvorKit.ECS.Generator/AlvorKit.ECS.Generator.csproj"
            OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
        <ProjectReference Include="..\Craftdig.World\Craftdig.World.csproj" />
    </ItemGroup>

</Project>
