# Directory to run the server from. The world data and server configs will be stored here
# Default: null
# RootPath =

# Logging level for the server. Options are: All, Trace, Debug, Info, Warn, Error, Fatal, Off
# Default : Debug
# LogLevel =

# Maximum number of players that can be connected at the same time
# Default: 20
# MaxPlayers = 20

# Server description shown to players in the server browser
# Default: null
# Description =

# Removes the allowlist check on player connections. Allows any player to join the server
# Default: false
PublicServer = false

# Disable the TLS port
# Default: false
DisableTls = false

# Enable the unencrypted TCP port
# Default: false
EnableRawTcp = false

# Path to the TLS certificate file
# Default: null
# CertPath =

# Path to the TLS private key file
# Default: null
# KeyPath =
