<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <Using Include="Craftdig.Unit">
            <Static>true</Static>
        </Using>
        <Using Include="Craftdig.AppUiSyntax">
            <Static>true</Static>
        </Using>
        <Using Include="AlvorKit.UiSyntax">
            <Static>true</Static>
        </Using>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Craftdig.Menus.Multiplayer\Craftdig.Menus.Multiplayer.csproj" />
        <ProjectReference
            Include="..\Craftdig.Menus.Singleplayer\Craftdig.Menus.Singleplayer.csproj" />
        <ProjectReference
            Include="$(AlvorKitRoot)src\AlvorKit.Injection.Graph\AlvorKit.Injection.Graph.csproj" />
    </ItemGroup>

</Project>
