<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ServerGarbageCollection>true</ServerGarbageCollection>
        <ApplicationIcon>..\..\res\Icons\Server.ico</ApplicationIcon>
        <AssemblyTitle>Craftdig Server</AssemblyTitle>
        <Product>Craftdig Server</Product>
    </PropertyGroup>

    <ItemGroup>
        <Using Include="AlvorKit.FastNoise2" />
        <Using Include="AlvorKit.XxHash" />
        <Using Include="Craftdig" />
        <Using Include="Craftdig.App" />
        <Using Include="Craftdig.Dimension" />
        <Using Include="Craftdig.Dimension.Backend" />
        <Using Include="Craftdig.Dimension.Server" />
        <Using Include="Craftdig.Dimension.Unit">
            <Static>true</Static>
        </Using>
        <Using Include="Craftdig.Module" />
        <Using Include="Craftdig.Native" />
        <Using Include="Craftdig.Protocol" />
        <Using Include="Craftdig.Server" />
        <Using Include="Craftdig.World" />
        <Using Include="Craftdig.World.Backend" />
        <Using Include="Craftdig.World.Server" />
        <Using Include="AlvorKit.Injection" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="AlvorKit.FastNoise2.Backend" Version="1.1.1.2" />
        <PackageReference Include="AlvorKit.XxHash.Backend" Version="0.8.3.13" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Craftdig.Native.Backend\Craftdig.Native.Backend.csproj" />
        <ProjectReference Include="..\..\src\Craftdig.Server\Craftdig.Server.csproj" />
    </ItemGroup>

</Project>
