<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <Using Include="Craftdig.Unit">
            <Static>true</Static>
        </Using>
        <Using Include="System.Collections.Frozen" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Craftdig.Identity\Craftdig.Identity.csproj" />
        <ProjectReference Include="..\Craftdig.Player.Frontend\Craftdig.Player.Frontend.csproj" />
        <ProjectReference Include="..\Craftdig.Protocol\Craftdig.Protocol.csproj" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Craftdig.Client.Security.Test" />
    </ItemGroup>

</Project>
