<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <ProjectReference Include="..\..\src\Craftdig.Server\Craftdig.Server.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="System.Diagnostics" />
        <Using Include="System.Net" />
        <Using Include="System.Net.Sockets" />
    </ItemGroup>

</Project>
