<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <ProjectReference Include="..\..\src\Craftdig.Client\Craftdig.Client.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Microsoft.IdentityModel.Tokens" />
        <Using Include="System.Text.Json" />
    </ItemGroup>

</Project>
