<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <Using Include="Craftdig.Unit">
            <Static>true</Static>
        </Using>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference
            Include="..\Craftdig.Dimension.Frontend\Craftdig.Dimension.Frontend.csproj" />
    </ItemGroup>

</Project>
