<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <AssemblyName>CraftdigServer</AssemblyName>
        <ApplicationIcon>..\..\res\Icons\Server.ico</ApplicationIcon>
        <AssemblyTitle>Craftdig Server</AssemblyTitle>
        <Product>Craftdig Server</Product>
    </PropertyGroup>

    <ItemGroup>
        <Using Include="AlvorKit.FastNoise2" />
        <Using Include="AlvorKit.XxHash" />
        <Using Include="Craftdig" />
        <Using Include="Craftdig.App" />
        <Using Include="Craftdig.Module" />
        <Using Include="Craftdig.Server" />
        <Using Include="Craftdig.Server.Cli" />
        <Using Include="Craftdig.World" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="AlvorKit.FastNoise2.Backend" Version="1.1.1.2" />
        <PackageReference Include="AlvorKit.XxHash.Backend" Version="0.8.3.13" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Craftdig.Server\Craftdig.Server.csproj" />
    </ItemGroup>

</Project>
