<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <AssemblyName>CraftdigServer</AssemblyName>
        <ApplicationIcon>..\..\res\Icons\Server.ico</ApplicationIcon>
        <AssemblyTitle>Craftdig Server</AssemblyTitle>
        <Product>Craftdig Server</Product>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Condition="!Exists('$(BindingsRoot)\AlvorKit.FastNoise2.Backend\AlvorKit.FastNoise2.Backend.csproj')"
            Include="AlvorKit.FastNoise2.Backend" Version="1.1.1.3" />
        <ProjectReference Condition="Exists('$(BindingsRoot)\AlvorKit.FastNoise2.Backend\AlvorKit.FastNoise2.Backend.csproj')"
            Include="$(BindingsRoot)\AlvorKit.FastNoise2.Backend\AlvorKit.FastNoise2.Backend.csproj" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Craftdig.Server\Craftdig.Server.csproj" />
    </ItemGroup>

</Project>
