<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <Using Include="AlvorKit.ECS.Indexed" />
        <Using Include="AlvorKit.Engine" />
        <Using Include="AlvorKit.Engine.Loop" />
        <Using Include="AlvorKit.OpenGL" />
        <Using Include="AlvorKit.OpenGL.Layer" />
        <Using Include="AlvorKit.Graphics2D" />
        <Using Include="AlvorKit.Graphics2D.Fonts" />
        <Using Include="Craftdig" />
        <Using Include="Craftdig.App" />
        <Using Include="Craftdig.App.Frontend" />
        <Using Include="Craftdig.Dimension" />
        <Using Include="Craftdig.Dimension.Frontend" />
        <Using Include="Craftdig.Dimension.Unit">
            <Static>true</Static>
        </Using>
        <Using Include="Craftdig.Menus" />
        <Using Include="Craftdig.Menus.Common.AppUiSyntax">
            <Static>true</Static>
        </Using>
        <Using Include="Craftdig.Module" />
        <Using Include="Craftdig.Module.Frontend" />
        <Using Include="Craftdig.Player.Frontend" />
        <Using Include="Craftdig.World" />
        <Using Include="Craftdig.World.Frontend" />
        <Using Include="AlvorKit.Windowing" />
        <Using Include="AlvorKit.UI" />
        <Using Include="AlvorKit.UI.UiSyntax">
            <Static>true</Static>
        </Using>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Craftdig.Player.Frontend\Craftdig.Player.Frontend.csproj" />
        <ProjectReference Include="..\Craftdig.World\Craftdig.World.csproj" />
        <ProjectReference Include="$(AlvorKitRoot)src\AlvorKit.ECS.Generator\AlvorKit.ECS.Generator.csproj"
            OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
        <ProjectReference Include="$(AlvorKitRoot)src\AlvorKit.UI\AlvorKit.UI.csproj" />
        <ProjectReference Include="$(AlvorKitRoot)src\AlvorKit.UI.Generator\AlvorKit.UI.Generator.csproj"
            OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    </ItemGroup>

</Project>
