<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <Using Include="Craftdig.Unit">
            <Static>true</Static>
        </Using>
        <Using Include="Craftdig.AppUiSyntax">
            <Static>true</Static>
        </Using>
        <Using Include="AlvorKit.UiSyntax">
            <Static>true</Static>
        </Using>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Craftdig.Player.Frontend\Craftdig.Player.Frontend.csproj" />
        <ProjectReference Include="..\Craftdig.World\Craftdig.World.csproj" />
        <ProjectReference Include="$(AlvorKitRoot)src\AlvorKit.ECS.Generator\AlvorKit.ECS.Generator.csproj"
            OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
        <ProjectReference Include="$(AlvorKitRoot)src\AlvorKit.UI\AlvorKit.UI.csproj" />
        <ProjectReference Include="$(AlvorKitRoot)src\AlvorKit.UI.Generator\AlvorKit.UI.Generator.csproj"
            OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    </ItemGroup>

</Project>
