<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <Using Include="Craftdig.Unit">
            <Static>true</Static>
        </Using>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Condition="!Exists('$(BindingsRoot)\AlvorKit.FastNoise2\AlvorKit.FastNoise2.csproj')"
            Include="AlvorKit.FastNoise2" Version="1.1.1.3" />
        <ProjectReference Condition="Exists('$(BindingsRoot)\AlvorKit.FastNoise2\AlvorKit.FastNoise2.csproj')"
            Include="$(BindingsRoot)\AlvorKit.FastNoise2\AlvorKit.FastNoise2.csproj" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Craftdig.Dimension.Backend\Craftdig.Dimension.Backend.csproj" />
        <ProjectReference Include="..\Craftdig.Native\Craftdig.Native.csproj" />
    </ItemGroup>

</Project>
