<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <Using Include="Craftdig.Unit">
            <Static>true</Static>
        </Using>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="$(AlvorKitRoot)src\AlvorKit.FastNoise2.Graph\AlvorKit.FastNoise2.Graph.csproj" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Craftdig.Dimension.Backend\Craftdig.Dimension.Backend.csproj" />
        <ProjectReference Include="..\Craftdig.Native\Craftdig.Native.csproj" />
    </ItemGroup>

</Project>
