<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <ServerGarbageCollection>true</ServerGarbageCollection>
        <ApplicationIcon>..\..\res\Icons\Client.ico</ApplicationIcon>
        <AssemblyTitle>Craftdig</AssemblyTitle>
        <Product>Craftdig</Product>
    </PropertyGroup>

    <ItemGroup>
        <Using Include="Craftdig.Unit">
            <Static>true</Static>
        </Using>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Craftdig.Menus\Craftdig.Menus.csproj" />
        <ProjectReference
            Include="$(AlvorKitRoot)src\AlvorKit.Injection.Graph\AlvorKit.Injection.Graph.csproj" />
    </ItemGroup>

</Project>
