<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <Using Include="AlvorKit.ECS.Indexed" />
        <Using Include="AlvorKit.Engine" />
        <Using Include="AlvorKit.Engine.Loop" />
        <Using Include="BigGustave" />
        <Using Include="AlvorKit.OpenGL" />
        <Using Include="AlvorKit.OpenGL.Layer" />
        <Using Include="AlvorKit.Graphics2D" />
        <Using Include="AlvorKit.Graphics2D.Fonts" />
        <Using Include="Craftdig" />
        <Using Include="Craftdig.App" />
        <Using Include="Craftdig.App.Frontend" />
        <Using Include="Craftdig.Dimension" />
        <Using Include="Craftdig.Dimension.Backend" />
        <Using Include="Craftdig.Dimension.Frontend" />
        <Using Include="Craftdig.Dimension.Unit">
            <Static>true</Static>
        </Using>
        <Using Include="Craftdig.Menus" />
        <Using Include="Craftdig.Menus.Common" />
        <Using Include="Craftdig.Menus.Common.AppUiSyntax">
            <Static>true</Static>
        </Using>
        <Using Include="Craftdig.Module" />
        <Using Include="Craftdig.Module.Frontend" />
        <Using Include="Craftdig.Player.Frontend" />
        <Using Include="Craftdig.World" />
        <Using Include="Craftdig.World.Backend" />
        <Using Include="Craftdig.World.Frontend" />
        <Using Include="AlvorKit.Windowing" />
        <Using Include="AlvorKit.UI" />
        <Using Include="AlvorKit.UI.UiSyntax">
            <Static>true</Static>
        </Using>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Craftdig.Dimension.Backend\Craftdig.Dimension.Backend.csproj" />
        <ProjectReference Include="..\Craftdig.Menus.Common\Craftdig.Menus.Common.csproj" />
    </ItemGroup>

</Project>
