<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <Using Include="BigGustave" />
        <Using Include="Craftdig.Unit">
            <Static>true</Static>
        </Using>
        <Using Include="Craftdig.AppUiSyntax">
            <Static>true</Static>
        </Using>
        <Using Include="AlvorKit.UiSyntax">
            <Static>true</Static>
        </Using>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Craftdig.Dimension.Backend\Craftdig.Dimension.Backend.csproj" />
        <ProjectReference Include="..\Craftdig.Menus.Common\Craftdig.Menus.Common.csproj" />
        <ProjectReference
            Include="$(AlvorKitRoot)src\AlvorKit.Injection.Graph\AlvorKit.Injection.Graph.csproj" />
    </ItemGroup>

</Project>
