<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ServerGarbageCollection>true</ServerGarbageCollection>
        <ApplicationIcon>..\..\res\Icons\Client.ico</ApplicationIcon>
        <AssemblyTitle>Craftdig</AssemblyTitle>
        <Product>Craftdig</Product>
    </PropertyGroup>

    <ItemGroup>
        <Using Include="Craftdig.Unit">
            <Static>true</Static>
        </Using>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Craftdig.Menus\Craftdig.Menus.csproj" />
        <ProjectReference Include="..\..\src\Craftdig.Native.Backend\Craftdig.Native.Backend.csproj" />
        <ProjectReference
            Include="..\..\src\Craftdig.Native.Frontend\Craftdig.Native.Frontend.csproj" />
        <ProjectReference
            Include="$(AlvorKitRoot)src\AlvorKit.Engine.LiveCode\AlvorKit.Engine.LiveCode.csproj" />
        <ProjectReference
            Include="$(AlvorKitRoot)src\AlvorKit.Engine.SourceUpdate\AlvorKit.Engine.SourceUpdate.csproj" />
        <ProjectReference
            Include="$(AlvorKitRoot)src\AlvorKit.LiveCode.Generator\AlvorKit.LiveCode.Generator.csproj"
            OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
        <ProjectReference Include="$(AlvorKitRoot)src\AlvorKit.Logging\AlvorKit.Logging.csproj" />
    </ItemGroup>

</Project>
