<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <Using Include="Craftdig" />
        <Using Include="Craftdig.App" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="AlvorEngine.FastNoiseLite" Version="1.0" />
        <PackageReference Include="Tomlyn" Version="0.19.0" />
        <PackageReference Include="ZString" Version="2.6.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="$(AlvorKitRoot)src\AlvorKit.ECS\AlvorKit.ECS.csproj" />
        <ProjectReference Include="$(AlvorKitRoot)src\AlvorKit.ECS.Generator\AlvorKit.ECS.Generator.csproj"
            OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
        <ProjectReference Include="$(AlvorKitRoot)src\AlvorKit.Injection\AlvorKit.Injection.csproj" />
        <ProjectReference Include="$(AlvorKitRoot)src\AlvorKit.Maths\AlvorKit.Maths.csproj" />
    </ItemGroup>

</Project>
