name: CI

on:
  push:
  pull_request:

permissions: read-all

jobs:
  ci:
    name: Build and lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          path: Craftdig
      - uses: actions/checkout@v7
        with:
          repository: samuelmasse/AlvorKit
          ssh-key: ${{ secrets.ALVORKIT_DEPLOY_KEY }}
          path: AlvorKit
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "10.0.x"
          dotnet-quality: ga
      - name: Generate AlvorKit sources
        working-directory: AlvorKit
        run: |
          dotnet run --project scripts/AlvorKit.Script.MathsGen -- --setup-local
          dotnet run --project scripts/AlvorKit.Script.Bindgen -- all --strict --setup-local
      - name: Build
        run: |
          dotnet restore Craftdig/Craftdig.slnx
          dotnet build Craftdig/Craftdig.slnx --no-restore
      - name: Lint
        working-directory: AlvorKit
        run: dotnet run --project scripts/AlvorKit.Script.Lint -- --repo-root ../Craftdig
